import { describe, it, expect } from 'vitest';
import { GENERATIVE_CYCLE, CONQUERING_CYCLE, getElementRelation, ELEMENT_ORDER } from '../src/elements';

describe('GENERATIVE_CYCLE', () => {
  it('follows the generative cycle', () => {
    expect(GENERATIVE_CYCLE['金']).toBe('水');
    expect(GENERATIVE_CYCLE['水']).toBe('木');
    expect(GENERATIVE_CYCLE['木']).toBe('火');
    expect(GENERATIVE_CYCLE['火']).toBe('土');
    expect(GENERATIVE_CYCLE['土']).toBe('金');
  });
});

describe('CONQUERING_CYCLE', () => {
  it('follows the conquering cycle', () => {
    expect(CONQUERING_CYCLE['金']).toBe('木');
    expect(CONQUERING_CYCLE['木']).toBe('土');
    expect(CONQUERING_CYCLE['土']).toBe('水');
    expect(CONQUERING_CYCLE['水']).toBe('火');
    expect(CONQUERING_CYCLE['火']).toBe('金');
  });
});

describe('getElementRelation', () => {
  it('same element → 比和', () => {
    expect(getElementRelation('金', '金')).toBe('比和');
    expect(getElementRelation('木', '木')).toBe('比和');
  });

  it('generates → 生', () => {
    expect(getElementRelation('金', '水')).toBe('生');
    expect(getElementRelation('木', '火')).toBe('生');
  });

  it('conquers → 剋', () => {
    expect(getElementRelation('金', '木')).toBe('剋');
    expect(getElementRelation('水', '火')).toBe('剋');
  });

  it('generated by → 被生', () => {
    expect(getElementRelation('水', '金')).toBe('被生');
    expect(getElementRelation('火', '木')).toBe('被生');
  });

  it('conquered by → 被剋', () => {
    expect(getElementRelation('木', '金')).toBe('被剋');
    expect(getElementRelation('火', '水')).toBe('被剋');
  });
});

describe('ELEMENT_ORDER', () => {
  it('has all 5 elements', () => {
    expect(ELEMENT_ORDER).toHaveLength(5);
    expect(new Set(ELEMENT_ORDER).size).toBe(5);
  });
});
