import { describe, it, expect } from 'vitest';
import { SHENG_CYCLE, KE_CYCLE, getRelationship, WUXING_ORDER } from '../src/wuxing';

describe('SHENG_CYCLE', () => {
  it('follows the generative cycle', () => {
    expect(SHENG_CYCLE['金']).toBe('水');
    expect(SHENG_CYCLE['水']).toBe('木');
    expect(SHENG_CYCLE['木']).toBe('火');
    expect(SHENG_CYCLE['火']).toBe('土');
    expect(SHENG_CYCLE['土']).toBe('金');
  });
});

describe('KE_CYCLE', () => {
  it('follows the conquering cycle', () => {
    expect(KE_CYCLE['金']).toBe('木');
    expect(KE_CYCLE['木']).toBe('土');
    expect(KE_CYCLE['土']).toBe('水');
    expect(KE_CYCLE['水']).toBe('火');
    expect(KE_CYCLE['火']).toBe('金');
  });
});

describe('getRelationship', () => {
  it('same element → 比和', () => {
    expect(getRelationship('金', '金')).toBe('比和');
    expect(getRelationship('木', '木')).toBe('比和');
  });

  it('generates → 生', () => {
    expect(getRelationship('金', '水')).toBe('生');
    expect(getRelationship('木', '火')).toBe('生');
  });

  it('conquers → 剋', () => {
    expect(getRelationship('金', '木')).toBe('剋');
    expect(getRelationship('水', '火')).toBe('剋');
  });

  it('generated by → 被生', () => {
    expect(getRelationship('水', '金')).toBe('被生');
    expect(getRelationship('火', '木')).toBe('被生');
  });

  it('conquered by → 被剋', () => {
    expect(getRelationship('木', '金')).toBe('被剋');
    expect(getRelationship('火', '水')).toBe('被剋');
  });
});

describe('WUXING_ORDER', () => {
  it('has all 5 elements', () => {
    expect(WUXING_ORDER).toHaveLength(5);
    expect(new Set(WUXING_ORDER).size).toBe(5);
  });
});
